name: test yml

on:
  workflow_dispatch:

jobs:
  Demo_Test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6

      - name: run tests
        run: mvn test -DbrowserType="chrome" -DheadlessExecution="true" -Dtest="google.tests.SeleniumTestNgDemoPOM"
      - name: Publish Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: 'target/surefire-reports/TEST-*.xml'    # Path to test results
          reporter: jest-junit        # Format of test results


